c = document.getElementById('canvas')
ctx = c.getContext('2d')
c.width = (window.innerWidth - 50)
c.height = (window.innerHeight - 50)
console.log(window.innerWidth - 50)
console.log(window.innerWidth)